version: "3.9"

services:

  sec-pipeline:

    build:
      context: .

    container_name: sec-filings-pipeline

    volumes:
      - ./data:/app/data
      - ./dbt:/app/dbt
      - ./src:/app/src

    working_dir: /app

    tty: true

    environment:
      SEC_USER_AGENT: ${SEC_USER_AGENT}
      PYTHONPATH: /app/src